name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    
    - name: Install AWS CDK CLI
      run: npm install -g aws-cdk@latest
    
    - name: Run tests
      run: |
        poetry run pytest --cov=infra --cov-report=xml
    
    - name: Lint with flake8
      run: |
        poetry run flake8 infra --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,cdk.out
        poetry run flake8 infra --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics --exclude=.venv,cdk.out
    

    
    - name: CDK Synth
      run: |
        cd infra
        poetry run cdk synth --all
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCOUNT_ID: "123456789012"
        JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION: "1"
    
    - name: CDK Diff (dry-run)
      run: |
        cd infra
        poetry run cdk diff --all || true
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCOUNT_ID: "123456789012"
        JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION: "1"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella